---

  - name: "say-local-date"
    signals:
      - order: "Wie spät ist es"
    neurons:
      - systemdate:
          say_template:
            - "Es ist {{ hours }} Uhr und {{ minutes }} Minuten"

  - name: "say-local-date-from-template"
    signals:
      - order: "Welcher Tag ist heute"
      - order: "Welches Datum ist heute"      
    neurons:
      - systemdate:
          file_template: "templates/de_systemdate_template.j2"

  - name: "tea-time"
    signals:
      - order: "Ist es Zeit für Tee"
    neurons:
      - systemdate:
          file_template: "templates/de_systemdate_template_tea.j2"
